# Generated by Django 2.1.7 on 2019-02-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(default='No description provided', max_length=500)),
                ('currentAction', models.IntegerField(default=0)),
                ('isDirty', models.BooleanField(default=True)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotapi.Action')),
            ],
        ),
    ]
