# Generated by Django 2.1.7 on 2019-02-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='currentAction',
            new_name='currentState',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='actions',
            new_name='states',
        ),
    ]
