# Generated by Django 2.1.7 on 2019-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapi', '0002_auto_20190224_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='states',
        ),
        migrations.AddField(
            model_name='device',
            name='states',
            field=models.ManyToManyField(to='iotapi.State'),
        ),
    ]
